#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	cat="bat" \
	mv="mv -iv" \
	rm="rm -vI" \
	rm="rm -r -vI" \
	tr="trash -f -v" \
	trd="trash -d -f -v" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	neo="neofetch" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner" \
	petty="pycodestyle" \
	ranger='. ranger' \
	disku='ncdu' \
	valgrind='valgrind -s --leak-check=full --show-leak-kinds=all --track-origins=yes' \
	speed='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -' \
	fonts='fc-cache -fv' \
	install='sudo pacman -Sy' \
	up='sudo pacman -Syu' \
	search='sudo pacman -Ss' \
	remove='sudo pacman -Rns' \
	ssh1='ssh ubuntu@54.237.57.5' \
	ssh2='ssh ubuntu@100.24.244.206' \
	sshlb='ssh ubuntu@52.86.186.202' \
	sshme='ssh alaaruht@162.0.209.26 -p 21098' \
	smail="email_extractor" \
	batlife="upower -i /org/freedesktop/UPower/devices/battery_BAT0" \
	gitinfo="onefetch" \
	vi="vim ." 

# Colorize commands when possible.
alias \
	ll="lsd -la" \
	ls="lsd -l" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer -7" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" 
	# z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
